# Generated by Django 5.1.4 on 2025-02-14 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_room_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
    ]
