# Generated by Django 5.1.4 on 2024-12-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
