# Generated by Django 5.1.4 on 2025-02-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_message_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('files', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
