# Generated by Django 5.1.4 on 2025-02-19 19:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_myfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myfiles',
            name='files',
        ),
        migrations.AlterField(
            model_name='myfiles',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
